### ISSUE TITLE
Is it possible to convert images on an API, not just local to the nuxt app?

### ISSUE THREAD

**Issue by rotanadan** [juliomrqz/nuxt-optimized-images#213]

**Comment by hdwebpros** [comment]
https://github.com/aceforth/nuxt-optimized-images/blob/develop/ISSUE_TEMPLATE.md Shows

> You are using an old version of issue templates. Please update to the new issue template workflow. Learn more

**Comment by mjzarrin** [comment]
I would like to know Is this package works on images that are proxied from external server.
```
proxy: {
    '/image': {
      target: 'https://my_image_host.com/image',
      pathRewrite: {
        '^/image': '/'
      }
    }
  },
```

**Comment by webcoderkz** [comment]
Interested as well, would be nice, if that would be possible.

**Comment by juliomrqz** [comment]
Sorry, but it can't work with external images. That's because this module relies on Webpack to load only local images. 

The Nuxt team is [planing to include a core feature](https://github.com/nuxt/nuxt.js/issues/6467#issuecomment-568179615) where external images can be optimized, don't know if it will include all the features form nuxt-optimizes-images.

I'm figuring out to support external images with this module, but I have not yet find a reliable approach. If you have some recommendation or an idea of how to do this, please open a feature request. Thanks 😎

**Comment by shadow81627** [comment]
There is a work in progress [nuxt image module](https://image.nuxtjs.org/) with support for optimized external images.
